<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE agenda [
<!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre,direccion,tlf,email,edad,estado_civil)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT estado_civil (#PCDATA)>
]>
<agenda>
<contacto>
<nombre></nombre>
<direccion></direccion>
<tlf></tlf>
<email></email>
<edad></edad>
<estado_civil></estado_civil>
</contacto>
</agenda>